"Pathogen call
call pathogen#runtime_append_all_bundles() 

" Core ========================================================================
filetype plugin on      " Determine file type
set nocompatible        " Disables compatibility with Vi
set autochdir           " Set path to current file's directory
set ofu=syntaxcomplete#Complete " set Omni completion
set hidden              " allow unsaved buffers to be hidden
set nofoldenable        " Disable folding
" gVim ========================================================================
if has('gui_running')
    set columns=115     " set screen width 
    set lines=51        " set window height
    set numberwidth=3   " set width of number 'gutter' column
    set guioptions-=T   " Get rid of toolbar
    " set guifont=DejaVu\ Sans\ Mono:h11 "set font:font size
endif
" Visuals =====================================================================
colorscheme molokai     " set color scheme
set colorcolumn=80      " make 80th column a different color
set textwidth=80        " new line when typing past 80 chars
set encoding=utf8       " use character encoding
set relativenumber      " set line numbers relative to the current line
set ruler               " Always show current position
set wrap!               " Turn off word wrapping
set scrolloff=5         " Keep X lines of padding at top/bottom
syntax on               " Turn on syntax highlighting
" Searching/Replacing =========================================================
set hlsearch            " Highlight searches (use :noh to unhighlight)
set incsearch           " Start searching when first character is typed
set ignorecase          " Ignore case when searching
set smartcase           " Case sensitive / search only if there is a capital
" Tabs ========================================================================
set expandtab           " Make tabs become spaces
set tabstop=4           " Makes tab equivalent to four spaces
set shiftwidth=4        " Set indentation levels of (<< and >>)
set softtabstop=4       " Makes tab in insert mode equivalent to four spaces
set autoindent          " Copies indentation from previous line for new lines
" backups =====================================================================
set nobackup
set nowb
set noswapfile
set history=1000        " Sets how many lines of history VIM has to remember
" Remapping Keys ==============================================================
"Displays current date
nmap <F5> a<C-R>=strftime("%Y-%m-%d %a %I:%M %p")<CR><Esc>
imap <F5> <C-R>=strftime("%Y-%m-%d %a %I:%M %p")<CR>
" guarantees that the NERDTrees for all tabs will be one and the same
map ,; :NERDTreeToggle \| :silent NERDTreeMirror<CR>
let NERDTreeShowBookmarks=1
